print("What  do you get when you cross a snowman with a vampire?")
input()
print("Frostbite")
print()
print("What do dentists call a astronaut\'s cavity")
input()
print("A black hole")
print()
print()
print('Knock knock.')
input()
print("Who's there?")
input()
print('Interrupting cow.')
input()
print('Interrupting cow wh', end='')
print('-MOO!')
input()
print("Wood-fired pizza.")
print("'You are confused.'")
print("What job is pizza gonna get now? AHAHAHAHAHAHA")
